### ISSUE TITLE
NotImplementedError: next time, baby

### ISSUE THREAD

**Issue by xuchengong** [tae898/multimodal-datasets#1]
Hi,

Thank you very much for your work.
In "extract-features.py", the four functions "extract_face_videos", "extract_visual_features", "extract_audio_features", and "extract_text_features" are not implemented yet. Will they be updated soon? Or do I need their updation to extract features?

Thank you very much!

**Comment by tae898** [comment]
Hey,

Yeah currently only `extract_face_features` is implemented. 
The other four methods, `extract_face_videos`, `extract_visual_features`, `extract_audio_features`, and `extract_text_features` are not implemented yet. If you have cool ideas, you can implement them yourselves and make a PR!

Tae

**Comment by xuchengong** [comment]
I see. Thank you for your reply!

I'm wondering how can I access the released EMISSOR representations and annotations of MELD, as mentioned in Section 4 of the paper `EMISSOR: A platform for capturing multimodal interactions as Episodic
Memories and Interpretations with Situated Scenario-based Ontological
References`?

![image](https://user-images.githubusercontent.com/64677684/127632978-924a867b-6350-40d8-8f32-452fa5840772.png)

Thanks!

**Comment by tae898** [comment]
Hey,

Sorry that they are not there yet. We are still working on it.

**Comment by xuchengong** [comment]
I see. Thank you for your reply!
