### ISSUE TITLE
looking for text modalities of IEMOCAO data set along with VAD score

### ISSUE THREAD

**Issue by akjadon** [tae898/multimodal-datasets#2]
HI ,

I am Anil Jadon doing my research on Emotion Detection  and for that i am trying to understand previous knowledge related to emotion.
i am looking for IEMOCAP data and in that i am looking for text modalities along with VAD score .

could you please confirm if below is the correct path and from where i can find the VAD score for the same.

https://github.com/tae898/multimodal-datasets/tree/main/IEMOCAP/raw-texts

i am bit confuse as i saw lot many pickle file having bigger text as compare to raw-texts json files. 

please help. and is there any detail understanding of this IEMOCAP dtaset.

Anil Jadon
8373910119

**Comment by tae898** [comment]
Hey,

I don't use the VAD scores since I just used the string emotion labels (e.g., neutral).
That's why my processed json files look like below:

`Ses01F_impro01_F000.json`:
```json
{
    "Utterance": "Excuse me.",
    "StartTime": 6.2901,
    "EndTime": 8.2357,
    "Speaker": "Female",
    "Emotion": "neutral",
    "SessionID": "Ses01"
}
```

As for the pickle files, they are `face-features`.

**Comment by akjadon** [comment]
Thanks  for this tea, it really helps.


Anil Jadon
